[package]
authors = ["Puzzled <support@pzzld.org>"]
categories = ["developer-tools"]
edition = "2024"
homepage = "https://github.com/FL03/bumper"
keywords = ["versioning", "semver"]
license = "Apache-2.0"
name = "bumper"
readme = "README.md"
repository = "https://github.com/FL03/bumper.git"
rust-version = "1.97.0"
version = "0.1.0"

[dependencies]
# parsing
nom = { default-features = false, optional = true, features = [], version = "8" }
num-traits = { default-features = false, version = "0.2" }
# serialization
serde = { optional = true, features = [], version = "1" }
serde_derive = { optional = true, features = [], version = "1" }
# macros & utilities
strum = { features = [], version = "0.28" }
thiserror = { default-features = false, version = "2" }

[features]
default = [
  "std",
]

full = ["default"]

# ********* [FF] Flags *********
parse = ["std", "nom"]

# ********* [FF] Standard Library *********
alloc = [
  "serde?/alloc",
]

std = [
  "alloc",
  "num-traits/std",
  "serde?/std",
  "strum/std",
  "thiserror/std",
]

# ********* [FF] Deps *********

nom = ["dep:nom"]

serde = [
  "dep:serde",
  "dep:serde_derive",
  "serde?/derive",
]
