[package]
name = "bumper-sdk"

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
name = "bumper"
path = "src/lib.rs"

[dependencies]
# parsing
nom = { optional = true, workspace = true }
# mathematics
num-traits = { workspace = true }
# serialization
serde = { optional = true, workspace = true }
serde_derive = { optional = true, workspace = true }
serde_json = { optional = true, workspace = true }
# macros & utilities
strum = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { features = ["plotters"], workspace = true }

[features]
default = [
  "std",
]

full = ["default"]

# ********* [FF] Flags *********
parse = [
  "std",
  "nom",
]

# ********* [FF] Standard Library *********
alloc = [
  "serde?/alloc",
]

std = [
  "alloc",
  "num-traits/std",
  "serde?/std",
  "strum/std",
  "thiserror/std",
]

# ********* [FF] Deps *********

nom = ["dep:nom"]

serde = [
  "dep:serde",
  "dep:serde_derive",
  "serde?/derive",
]

# ********* [tests] *********
[[test]]
name = "parse"
required-features = ["parse"]
